### ISSUE TITLE
Run locally without acess aws s3

### ISSUE THREAD

**Issue by eletroswing** [NicolasLopes7/shipthing#9]
Is it possible to use Minio in Docker Compose to emulate s3 and thus run it locally?

**Comment by meiazero** [comment]
I've tried to implement it in docker compose, but I haven't tested it yet because I don't know how to automate the creation of the bucket. 


```yaml
version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: shipthing-redis
    restart: always
    ports:
    - '6379:6379'
    command: redis-server --loglevel warning --requirepass passwd


  minio:
    image: quay.io/minio/minio
    container_name: shipthing-minio-storage
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: secret-password
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-storage:/data
    command: server /data --console-address ':9001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-storage:

```

**Comment by eletroswing** [comment]
i think you need the minio cli to create the bucket inside the docker container

**Comment by meiazero** [comment]
I found this on stack overflow and, in my tests, it works well.

```yaml
version: '3.8'

services:

# redis instance

  minio:
    image: quay.io/minio/minio
    container_name: shipthing-minio-storage
    environment:
      MINIO_ROOT_USER: shipthing
      MINIO_ROOT_PASSWORD: secret-password
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-storage:/data
    command: server /data --console-address ':9001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set shipthing http://minio:9000 shipthing secret-password;
      /usr/bin/mc mb shipthing/shipthing;
      /usr/bin/mc policy set public shipthing/shipthing;
      exit 0;
      "

volumes:
  minio-storage:

```
